name: Auto Contributions

on:
  schedule:
    - cron: "0 8 * * *" # Adjust the time as per your preference.
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate 3D Profile SVGs
    steps:
      - uses: actions/checkout@v4
      - uses: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name "Shweta Dudye"
          git config user.email "shwetadudye@example.com"
          git add .
          git commit -m "Updated 3D Profile SVGs."
          git push
